In [1]:
import numpy as np
import sys
#https://youtu.be/QUT1VHiLmmI?si=VR-VUb7JCUbheyly

List are slow but NumPy is very fast.
 .   

*   NumPy uses fixed types
*   NumPy has no type checking when checking obejcts.
*   Numpy uses contiguous memory.
       *  SIMD Vector Prcoessing
       *  Effective Cache Utilization
  


 NumPy uses int32 to represent val like 5. However, lists represent 5 with 4 different things, Size, Reference Count,  Object Type, Object Value. I.E lists uses way more bytes than NumPy.





In [13]:
a = np.array([1,2,3], dtype = 'int16')
a

array([1, 2, 3], dtype=int16)

In [5]:

b = np.array([[9.0,8.0,7.0] , [6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [8]:
#Get Dimension
a.ndim


1

In [9]:
b.ndim

2

In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [14]:
a.dtype

dtype('int16')

In [15]:
#get size
a.itemsize

2

In [17]:
#Total Size
a.size * a.itemsize
a.nbytes

6

In [19]:
c = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [20]:
c.shape

(2, 7)

In [22]:
# get specific element [row , column]
c[1,5]
c[1,-2] # Same thing

13

In [23]:
# Specific Row
c[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Specific Column
c[:, 2]

array([ 3, 10])

In [30]:
# Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]
c[0, 1:-1:2]


array([2, 4, 6])

In [32]:
# Change values
c[1,5] = 20
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [33]:
c[:,2] = [1,2]
c

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3-d example

In [37]:
# 3-d array example

d = np.array([[[1,2],[3,4]] , [[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [39]:
# get specific element [get outside then in]

print(d[0,1,1])
print(d[:,1,:])

4
[[3 4]
 [7 8]]


In [49]:
# All 0s matrix
print(np.zeros(5))
print(np.zeros((2,3)))


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
#print all ones
print(np.ones((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [51]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [52]:
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [54]:
#random decimal numbers
np.random.rand(3,2)

array([[0.29457032, 0.85843408],
       [0.0077332 , 0.85820497],
       [0.03800743, 0.12084734]])

In [56]:
#Random_Integer
np.random.randint(7 , size=(3,3))

array([[1, 0, 1],
       [5, 6, 3],
       [2, 2, 3]])

In [57]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [63]:
d= np.ones((5,5))
d[1:4,1:4] = 0
d[2,2] = 9
d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ba = np.array([1,2,3])
#re= ba # if ya do this, then both re and ba point to same array
re = ba.copy()


In [64]:
e = np.array([3,4,5,6,7])
print(e+2)
print(e-2)
print(e*2)
print(e/2)

[5 6 7 8 9]
[1 2 3 4 5]
[ 6  8 10 12 14]
[1.5 2.  2.5 3.  3.5]


In [65]:
np.sin(e)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

# **Linear Algebra**

In [69]:
ares = np.ones((2,3))
venus = np.full((3,2) ,2)
print(ares)
print(venus)
print(np.matmul(ares,venus))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [73]:
certs = np.identity(3)
np.linalg.det(certs)

1.0

# **Statstics**

In [75]:
therere = np.array([[1,2,3,4], [5,6,7,8]])
print(np.min(therere))
print(np.max(therere))
print(np.min(therere, axis=1))
print(np.sum(therere))

1
8
[1 5]
36


# **Reorganizing Arrays**

In [78]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print(before.shape)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [79]:
#Vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
#Horizontal Stacking Vectors
h1= np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [86]:
# filedata = np.genfromtxt('data.txt' , delimeter = ',')
# filedata[filedata > 50] makes it where it prints vals only over 50 in form of 1-D horizontal array
x = np.random.normal(size=50) # generates 50 random independ vars
print(x)
y = np.random.normal(loc=50, scale=1, size=50)
print(y)
z = x + y

[ 0.28332714 -0.17984002 -0.04164841  0.10209974 -0.22645112 -0.39114622
  0.05641596 -0.65290156  0.35539319  1.07866029 -0.02168766 -0.54801354
  0.29355412  0.3619937  -1.14770799  0.0427832  -1.07768865  1.08932412
  0.34430529 -0.01220285 -2.18047953  1.45311261  0.7815498   0.42876861
  1.70019628  0.40185274 -1.57724404  1.13175341 -1.21964383 -1.25625088
  0.03385736 -1.80363851  0.70432947  0.56887863  1.2332113  -0.37006358
  0.44299053  0.79663628 -0.32235315  0.1086167  -0.74238779  0.31802657
  1.26791033  1.47397981 -0.87943144  0.62575268  0.74357527 -0.29690378
  0.65025424  0.01423624]
[47.89900773 49.11311008 50.10866068 51.11911903 50.04532774 47.44184332
 48.75614698 49.58127826 50.20538309 48.66673116 50.48285604 49.60209329
 49.81186655 50.00886309 50.90505641 50.89979125 49.53622291 50.15378375
 49.19049327 51.18104462 49.82268945 49.62769187 50.48066829 49.09069841
 50.95716881 49.2006387  48.67670521 48.60920601 50.68169328 49.65270675
 49.46422434 49.70322449 

In [87]:
# correlation matrix between x and z. off-diagonal elements give correlation btwn x and z
np.corrcoef(x,z)

array([[1.        , 0.67123598],
       [0.67123598, 1.        ]])

In [88]:
# keeps random gen data staying the same every run
rng = np.random.default_rng (1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng (1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]
