In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.0+cu121


In [12]:
#Torch Tensors
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

#vector
vector = torch.tensor(np.array([7, 7]))
print(vector)
print(vector.ndim)
print(vector.shape)

# Matrix
Matrix = torch.tensor(np.array([[7, 8],
                       [9, 10]]))
print(Matrix)
print(Matrix.ndim)
print(Matrix.shape)

# Tensor
tensor = torch.tensor(np.array([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]))
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor(7)
0
7
tensor([7, 7])
1
torch.Size([2])
tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])
tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [14]:
rng = np.random.default_rng (1303)
print(rng.normal(size=(3,4)))

# Other way
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)
print(random_tensor.dtype)

[[ 0.81896526 -0.21497121 -2.03072919  0.22681229]
 [-0.82806113 -0.94971965  0.09748025  1.13071035]
 [-0.503177   -1.6146684  -0.51143783  1.30857567]]
tensor([[0.7642, 0.3925, 0.2051, 0.7635],
        [0.2107, 0.2727, 0.4264, 0.6793],
        [0.0422, 0.5040, 0.4414, 0.0194]])
torch.float32


In [15]:
ones = torch.ones(size=(3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [18]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
print(zero_to_ten)
ten_zeros = torch.zeros_like(input=zero_to_ten)
print(ten_zeros)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [19]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

print(float_32_tensor.shape)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

torch.Size([3])
torch.float32
cpu


In [22]:
# tensor * tensor
# torch.matmul(tensor, tensor)
# tensor @ tensor
# ways to multiply tensors
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

#Same thing
torch.mm(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [30]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input. Needs to be same as colulmn of tensor A
                         out_features=2) # out_features = describes outer value, changes amount of columns
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[1.5595, 1.2761],
        [3.8145, 2.2439],
        [6.0695, 3.2117]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 2])


In [31]:
x = torch.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [32]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0
